# Generated by Django 2.1.3 on 2018-11-18 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_dummy2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('prev_business_seats', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('business_seats', models.IntegerField(default=0)),
                ('origin', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='changes',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.Flight'),
        ),
    ]
