# Generated by Django 2.1.3 on 2018-11-18 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_auto_20181118_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
