# Generated by Django 2.1.3 on 2018-11-24 12:26

from django.db import migrations
import enumfields.fields
import sas_api.requester


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_flight_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dummy',
        ),
        migrations.DeleteModel(
            name='Dummy2',
        ),
        migrations.RenameField(
            model_name='changes',
            old_name='prev_business_seats',
            new_name='prev_seats',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='business_seats',
            new_name='seats',
        ),
        migrations.AddField(
            model_name='flight',
            name='cabin',
            field=enumfields.fields.EnumField(default='b', enum=sas_api.requester.CabinClass, max_length=10),
            preserve_default=False,
        ),
    ]
