# Generated by Django 2.1.3 on 2018-12-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0006_apierror'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='seats',
            new_name='business_seats',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='cabin',
        ),
        migrations.AddField(
            model_name='flight',
            name='plus_seats',
            field=models.IntegerField(default=0),
        ),
    ]
